name : 02 - Workflow Events

on:
  push:  
  pull_request:
  schedule:
     - cron: "0/5 * * * *"
  workflow_dispatch:     

jobs: 
   echo:
    runs-on: ubuntu-latest
    steps:
      - name: show the trigger by event
        run: echo "I have been triggered by a(n) ${{github.event_name}} event"   
