name: 13-caching

on:
  workflow_dispatch:
    inputs:
      use-cache:  
        description: Whether to execute cache step  
        type: boolean
        default: true
      node-version:
        description: node version
        type: choice
        options:
           - 18.x
           - 20.x
           - 21.x
        default: 20.x      
jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: 13-caching/react-app  
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: node setup
        uses: actions/setup-node@v3
        with:  
          node-version: ${{ inputs.node-version }} 
      - name: download cache
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache
        with:
          path: 13-caching/reactapp/node_modules
          key: deps-node-modules-{{hashfiles('13-caching/react-app/package-lock.json')}}    
      - name: Install dependencies
        if: steps.cache.outputs.cache.hit != 'true'
        run: npm ci         
      - name: npm run test
        run: npm run test        
      - name: npm build
        run: npm run build  
      - name: deploying to nonprod
        run: echo "deploing on nonprod"    
